language: python
dist: focal
python:
  - "3.8"
  - "3.9"
install:
  - python setup.py install
virtualenv:
  system_site_packages: false
script:
  - python3 -m unittest tests/test_contain.py || python -m unittest tests/test_contain.py